# -*- coding: utf-8 -*-
"""Untitled6.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/11yto0lt1D9IibL1OTHNIt7mGCyui_jCp
"""

total = 0
for i in range(1,6):
  print(f"\nItem {i}")

  price =float(input("Enter the price of the item: "))
  quantity = int(input("Enter the quantity of the item: "))

  total += price * quantity

discount = 0
if total>100:
  discount = total *0.10

final_amount = total - discount


print("\n______BILL SUMMARY______")
print("Original Total = ",total)
print("Discount =",discount)
print("Final Amount =",final_amount)

"""


total = 0

for i in range(1, 6):
    print(f"\nItem {i}")

    # price input validation
    while True:
        try:
            price = float(input("Enter price: "))
            break
        except ValueError:
            print("Invalid input! Enter numeric value.")

    # quantity input validation
    while True:
        try:
            qty = int(input("Enter quantity: "))
            break
        except ValueError:
            print("Invalid input! Enter integer value.")

    total += price * qty

discount = 0
if total > 100:
    discount = total * 0.10

final_amount = total - discount

print("\n----- BILL SUMMARY -----")
print("Original Total =", total)
print("Discount =", discount)
print("Final Amount =", final_amount)
"""

total = 0

for i in range(1, 6):
    print(f"\nItem {i}")

    # price input validation
    while True:
        try:
            price = float(input("Enter price: "))
            break
        except ValueError:
            print("Invalid input! Enter numeric value.")

    # quantity input validation
    while True:
        try:
            qty = int(input("Enter quantity: "))
            break
        except ValueError:
            print("Invalid input! Enter integer value.")

    total += price * qty

discount = 0
if total > 100:
    discount = total * 0.10

final_amount = total - discount

print("\n----- BILL SUMMARY -----")
print("Original Total =", total)
print("Discount =", discount)
print("Final Amount =", final_amount)